name: detective
root: ~/

windows:
  - logs:
      layout: tiled
      panes:
        - carla:
          - cd /home/e5_5044/Desktop/carla/
          - ./CarlaUE4.sh -opengl
        - GPU:
          - watch nvidia-smi
        - falsifier:
          - cd ~/autoDetective
          - source venv/bin/activate
          - python falsifier.py
        - simulator:
          - cd ~/autoDetective
          - source venv/bin/activate
          - python simulator.py
