name: detective
root: ~/

windows:
  - logs:
      layout: tiled
      panes:
        - carla:
          - cd Desktop/carla
          - ./CarlaUE4.sh -opengl
        - GPU:
          - watch nvidia-smi
        - falsifier:
          - cd ~/Desktop/k_explorer
          - poetry shell
          - python falsifier.py
        - simulator:
          - cd ~/Desktop/k_explorer
          - poetry shell
          - python simulator.py
